package aliases

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteShellScripts regenerates shell/aliases.{bash,fish,ps1} from the current aliases file.
func WriteShellScripts(configDir string) error {
	path := FilePath(configDir)
	f, err := Load(path)
	if err != nil {
		return err
	}
	dir := ShellDir(configDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	bash, err := generateBashZsh(f)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "aliases.bash"), []byte(bash), 0o644); err != nil {
		return err
	}
	fish, err := generateFish(f)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "aliases.fish"), []byte(fish), 0o644); err != nil {
		return err
	}
	ps, err := generatePowerShell(f)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "aliases.ps1"), []byte(ps), 0o644)
}

func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, `'`, `'\''`) + "'"
}

func generateBashZsh(f *File) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by mb alias — do not edit manually.\n")
	names := SortedDisplayNames(f)
	for _, name := range names {
		e, ok, err := PickShellEntryForDisplayName(f, name)
		if err != nil {
			return "", err
		}
		if !ok {
			continue
		}
		if err := ValidateName(name); err != nil {
			return "", fmt.Errorf("alias %q: %w", name, err)
		}
		if err := ValidateEntry(e); err != nil {
			return "", fmt.Errorf("alias %q: %w", name, err)
		}
		var parts []string
		for _, a := range e.Command {
			parts = append(parts, shellSingleQuote(a))
		}
		line := strings.Join(parts, " ")
		fmt.Fprintf(&b, "%s() { command %s \"$@\"; }\n", name, line)
	}
	return b.String(), nil
}

func generateFish(f *File) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by mb alias — do not edit manually.\n")
	names := SortedDisplayNames(f)
	for _, name := range names {
		e, ok, err := PickShellEntryForDisplayName(f, name)
		if err != nil {
			return "", err
		}
		if !ok {
			continue
		}
		if err := ValidateName(name); err != nil {
			return "", fmt.Errorf("alias %q: %w", name, err)
		}
		if err := ValidateEntry(e); err != nil {
			return "", fmt.Errorf("alias %q: %w", name, err)
		}
		fmt.Fprintf(&b, "function %s\n", name)
		var parts []string
		for _, a := range e.Command {
			parts = append(parts, shellSingleQuote(a))
		}
		line := strings.Join(parts, " ")
		fmt.Fprintf(&b, "    command %s $argv\n", line)
		b.WriteString("end\n")
	}
	return b.String(), nil
}

func generatePowerShell(f *File) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by mb alias — do not edit manually.\n")
	names := SortedDisplayNames(f)
	for _, name := range names {
		e, ok, err := PickShellEntryForDisplayName(f, name)
		if err != nil {
			return "", err
		}
		if !ok {
			continue
		}
		if err := ValidateName(name); err != nil {
			return "", fmt.Errorf("alias %q: %w", name, err)
		}
		if err := ValidateEntry(e); err != nil {
			return "", fmt.Errorf("alias %q: %w", name, err)
		}
		var parts []string
		for _, a := range e.Command {
			parts = append(parts, escPSArg(a))
		}
		fmt.Fprintf(&b, "function %s { & %s $args }\n", name, strings.Join(parts, " "))
	}
	return b.String(), nil
}

func escPSArg(s string) string {
	// Single-quote for PowerShell literal args
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
